language: python

python:
  - '3.6'
  - '3.6-dev'
  - '3.7-dev'
  - 'nightly'

install:
  - pip install -r requirements.txt
  - python setup.py install

script:
  - mypy --ignore-missing-imports -m graphique
  - python setup.py test
